export const AUTH_USER = 'AUTH_USER'
export const UNAUTH_USER = 'UNAUTH_USER'
export const AUTH_REQ = 'AUTH_REQ'
export const AUTH_ERROR = 'AUTH_ERROR'
export const DELETE_AUTHINFO = 'DELETE_AUTHINFO'
export const CONFIGURE = 'CONFIGURE'
export const WRITE_TOKEN_STATUS = 'TOKEN_STATUS'
export const RESET_AUTH_ERROR = 'RESET_AUTH_ERROR'
